# Práctica 03 - Python

In [1]:
import sys
import platform
import numpy as np
import pandas as pd

print("Python      :", sys.version)
print("Implementación:", platform.python_implementation())
print("NumPy       :", np.__version__)
print("pandas      :", pd.__version__)

assert sys.version_info[:2] == (3, 12), "Esta práctica requiere Python 3.12"
print("\nEntorno verificado correctamente.")

Python      : 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
Implementación: CPython
NumPy       : 2.5.3
pandas      : 3.0.6

Entorno verificado correctamente.


## Ejercicio 1 - Catálogo de productos como lista

In [2]:
catalogo = [
    "Auriculares BT", 59.90,
    "Smartwatch S2", 149.00,
    "Tablet 10", 219.00,
    "Cargador USB-C", 18.50,
    "Cafetera Expres", 189.00,
    "Robot Aspirador", 279.00,
]

print("Elementos en la lista:", len(catalogo))
print("Productos en el catálogo:", len(catalogo) // 2)

# los nombres van en las posiciones pares y los precios en las impares
nombres = catalogo[0::2]
precios = catalogo[1::2]
print(nombres)
print(precios)

# busco la posición del nombre y el precio está justo detrás
pos_nombre = catalogo.index("Robot Aspirador")
print("Precio del Robot Aspirador:", catalogo[pos_nombre + 1])

ultimos_tres_nombres = nombres[-3:]
print(ultimos_tres_nombres)

precio_medio = round(sum(precios) / len(precios), 2)
print("Precio medio:", precio_medio)

Elementos en la lista: 12
Productos en el catálogo: 6
['Auriculares BT', 'Smartwatch S2', 'Tablet 10', 'Cargador USB-C', 'Cafetera Expres', 'Robot Aspirador']
[59.9, 149.0, 219.0, 18.5, 189.0, 279.0]
Precio del Robot Aspirador: 279.0
['Cargador USB-C', 'Cafetera Expres', 'Robot Aspirador']
Precio medio: 152.4


## Ejercicio 2 - Inventario multialmacén con listas anidadas

In [3]:
inventario = [
    ["ALM-NORTE", "Robot Aspirador", 34, 201.50],
    ["ALM-NORTE", "Monitor 27", 58, 142.00],
    ["ALM-SUR",   "Silla Ergonomica", 12, 178.90],
    ["ALM-SUR",   "Robot Aspirador", 7, 201.50],
    ["ALM-ESTE",  "Cafetera Expres", 41, 131.20],
    ["ALM-ESTE",  "Monitor 27", 25, 142.00],
]

print("Producto de la 4ª fila:", inventario[3][1])

valor_stock = []
for fila in inventario:
    producto = fila[1]
    valor_fila = round(fila[2] * fila[3], 2)
    valor_stock.append([producto, valor_fila])
print(valor_stock)

valor_total = round(sum(linea[1] for linea in valor_stock), 2)
print("Valor inmovilizado total:", valor_total)

# el ALM-SUR ocupa las filas 2 y 3, así que van seguidas
filas_alm_sur = inventario[2:4]
valor_alm_sur = round(sum(fila[2] * fila[3] for fila in filas_alm_sur), 2)
print("Valor ALM-SUR:", valor_alm_sur)

Producto de la 4ª fila: Robot Aspirador
[['Robot Aspirador', 6851.0], ['Monitor 27', 8236.0], ['Silla Ergonomica', 2146.8], ['Robot Aspirador', 1410.5], ['Cafetera Expres', 5379.2], ['Monitor 27', 3550.0]]
Valor inmovilizado total: 27573.5
Valor ALM-SUR: 3557.3


El slicing `inventario[2:4]` funciona porque sé que esas dos filas del ALM-SUR están juntas, pero si se añade una fila nueva o los almacenes se desordenan, ese mismo slice me daría datos de otro almacén sin avisar de nada. Por eso no es fiable filtrar por posición: hay que filtrar comparando el valor (`fila[0] == "ALM-SUR"`), que no depende de dónde esté cada fila.

## Ejercicio 3 - Manipulación destructiva y copias de listas

In [4]:
precios_originales = [59.90, 149.00, 219.00, 18.50, 189.00, 279.00]

# esto no copia la lista, apunta al mismo objeto
precios_rebajados = precios_originales
precios_rebajados[0] = 49.90
print(precios_rebajados)
print(precios_originales)

precios_originales[0] = 59.90
copia_con_list = list(precios_originales)
copia_con_slice = precios_originales[:]

copia_con_list[0] = 0.01
copia_con_slice[1] = 0.02
print(precios_originales)
print(copia_con_list)
print(copia_con_slice)

rebajada = precios_originales[:]
for i in range(len(rebajada)):
    rebajada[i] = round(rebajada[i] * 0.90, 2)
print(rebajada)

rebajada.extend([99.90, 45.00])
rebajada.insert(2, 129.90)
print(rebajada)

del rebajada[4]
descartado = rebajada.pop()
print(descartado, rebajada)

print(id(precios_originales), id(copia_con_list), id(copia_con_slice))
print(precios_originales is copia_con_list)

[49.9, 149.0, 219.0, 18.5, 189.0, 279.0]
[49.9, 149.0, 219.0, 18.5, 189.0, 279.0]
[59.9, 149.0, 219.0, 18.5, 189.0, 279.0]
[0.01, 149.0, 219.0, 18.5, 189.0, 279.0]
[59.9, 0.02, 219.0, 18.5, 189.0, 279.0]
[53.91, 134.1, 197.1, 16.65, 170.1, 251.1]
[53.91, 134.1, 129.9, 197.1, 16.65, 170.1, 251.1, 99.9, 45.0]
45.0 [53.91, 134.1, 129.9, 197.1, 170.1, 251.1, 99.9]
1542576903744 1542577055616 1542576903872
False


## Ejercicio 4 - Cola de pedidos pendientes

In [5]:
cola = ["PED-10021", "PED-10007", "PED-10044", "PED-10012", "PED-10033", "PED-10008"]

cola_invertida = cola[::-1]
print(cola_invertida)

cola_ordenada = sorted(cola)
print(cola_ordenada)
print(cola)

cola.sort(reverse=True)
print(cola)

atendidos = [cola.pop(0), cola.pop(0)]
print(atendidos)

cola.insert(0, "PED-99999")
print(cola)

total_pedidos = len(atendidos) + len(cola)
avance_pct = round(len(atendidos) / total_pedidos * 100, 1)
print(f"Atendidos: {len(atendidos)} | Pendientes: {len(cola)} | Avance: {avance_pct} %")

['PED-10008', 'PED-10033', 'PED-10012', 'PED-10044', 'PED-10007', 'PED-10021']
['PED-10007', 'PED-10008', 'PED-10012', 'PED-10021', 'PED-10033', 'PED-10044']
['PED-10021', 'PED-10007', 'PED-10044', 'PED-10012', 'PED-10033', 'PED-10008']
['PED-10044', 'PED-10033', 'PED-10021', 'PED-10012', 'PED-10008', 'PED-10007']
['PED-10044', 'PED-10033']
['PED-99999', 'PED-10021', 'PED-10012', 'PED-10008', 'PED-10007']
Atendidos: 2 | Pendientes: 5 | Avance: 28.6 %


## Ejercicio 5 - Funciones propias para el cálculo de importes

In [6]:
def calcular_importe(unidades, precio_unitario, descuento_pct=0):
    """Importe neto de una línea de pedido, con descuento opcional."""
    bruto = unidades * precio_unitario
    return round(bruto * (1 - descuento_pct / 100), 2)


def desglose_pedido(unidades, precio_unitario, descuento_pct=0):
    """Devuelve (imp_bruto, dto, imp_neto) de un pedido."""
    imp_bruto = round(unidades * precio_unitario, 2)
    imp_neto = calcular_importe(unidades, precio_unitario, descuento_pct)
    dto = round(imp_bruto - imp_neto, 2)
    return imp_bruto, dto, imp_neto


imp_bruto, dto, imp_neto = desglose_pedido(unidades=3, precio_unitario=59.90, descuento_pct=10)
print(f"Bruto: {imp_bruto} | Descuento: {dto} | Neto: {imp_neto}")

help(calcular_importe)

pedidos_ejemplo = [(3, 59.90, 10), (1, 279.00, 0), (5, 18.50, 20), (2, 149.00, 5), (4, 89.90, 15)]
importes_pedidos = [calcular_importe(u, p, d) for u, p, d in pedidos_ejemplo]

print(importes_pedidos)
print("Máximo:", max(importes_pedidos))
print("Mínimo:", min(importes_pedidos))
print("Ordenados:", sorted(importes_pedidos))
print("Nº pedidos:", len(importes_pedidos), "| Total:", round(sum(importes_pedidos), 2))

Bruto: 179.7 | Descuento: 17.97 | Neto: 161.73
Help on function calcular_importe in module __main__:

calcular_importe(unidades, precio_unitario, descuento_pct=0)
    Importe neto de una línea de pedido, con descuento opcional.

[161.73, 279.0, 74.0, 283.1, 305.66]
Máximo: 305.66
Mínimo: 74.0
Ordenados: [74.0, 161.73, 279.0, 283.1, 305.66]
Nº pedidos: 5 | Total: 1103.49


## Ejercicio 6 - Normalización de códigos SKU con métodos

In [7]:
skus_originales = [
    "  elc-0012-es ", "HOG-0045-ES", "dep-0003-pt  ",
    "ofi-0021-es", "  ELC-0012-ES", "hog-0099-fr ",
]

skus_ok = []
for sku in skus_originales:
    skus_ok.append(sku.strip().upper())
print(skus_ok)

print(skus_ok.count("ELC-0012-ES"))
print(skus_ok.index("OFI-0021-ES"))

trozos_sku = []
for sku in skus_ok:
    trozos_sku.append(sku.split("-"))
print(trozos_sku)

skus_solo_es = []
for familia, numero, pais in trozos_sku:
    if pais == "ES":
        skus_solo_es.append(f"{familia}-{numero}-{pais}".replace("-", "."))
print(skus_solo_es)

print(" | ".join(skus_solo_es))

['ELC-0012-ES', 'HOG-0045-ES', 'DEP-0003-PT', 'OFI-0021-ES', 'ELC-0012-ES', 'HOG-0099-FR']
2
3
[['ELC', '0012', 'ES'], ['HOG', '0045', 'ES'], ['DEP', '0003', 'PT'], ['OFI', '0021', 'ES'], ['ELC', '0012', 'ES'], ['HOG', '0099', 'FR']]
['ELC.0012.ES', 'HOG.0045.ES', 'OFI.0021.ES', 'ELC.0012.ES']
ELC.0012.ES | HOG.0045.ES | OFI.0021.ES | ELC.0012.ES


## Ejercicio 7 - Paquetes, importaciones y módulo propio

In [8]:
import math
print("sqrt(2809) =", math.sqrt(2809))

from math import pi, ceil
palets_necesarios = ceil(1375 / 24)
print("Palés necesarios:", palets_necesarios, "| pi =", round(pi, 4))

import numpy as np
import pandas as pd
print("NumPy:", np.__version__, "| pandas:", pd.__version__)

import random
random.seed(42)
notas_clientes = [random.randint(1, 5) for _ in range(10)]
print(notas_clientes)

sqrt(2809) = 53.0
Palés necesarios: 58 | pi = 3.1416
NumPy: 2.5.3 | pandas: 3.0.6
[1, 1, 3, 2, 2, 2, 1, 5, 1, 5]


Con la semilla fija, `random` genera siempre la misma secuencia de números, así que si el profesor ejecuta la misma celda le va a salir exactamente el mismo resultado que a mí.

In [9]:
import sys
sys.path.append("../src")

from utilidades import calcular_importe, clasificar_ticket

print(calcular_importe(4, 89.90, 15))
print(clasificar_ticket(305.66))

305.66
Medio


## Ejercicio 8 - Del cálculo con listas al cálculo vectorizado

In [10]:
unidades_pedido = [3, 1, 5, 2, 4, 6, 2, 8, 3, 1]
precios_pedido = [59.90, 279.00, 18.50, 149.00, 89.90, 27.50, 219.00, 14.90, 64.00, 239.00]

try:
    resultado = unidades_pedido * precios_pedido
except TypeError as e:
    print("TypeError:", e)

TypeError: can't multiply sequence by non-int of type 'list'


Con listas de Python, `*` significa repetir la secuencia, no multiplicar elemento a elemento, así que solo acepta un entero a la derecha; por eso multiplicar dos listas revienta con `TypeError`.

In [11]:
arr_unidades = np.array(unidades_pedido)
arr_precios = np.array(precios_pedido)
print(arr_unidades.dtype, arr_unidades.shape)
print(arr_precios.dtype, arr_precios.shape)

importes = arr_unidades * arr_precios
print(importes)
print("Total:", round(importes.sum(), 2))

importes_con_recargo = importes * 1.04
print(np.round(importes_con_recargo, 2))
print("Total con recargo:", round(importes_con_recargo.sum(), 2))

array_mixto = np.array([1, "dos", 3.0, True])
print(array_mixto, array_mixto.dtype)

int64 (10,)
float64 (10,)
[179.7 279.   92.5 298.  359.6 165.  438.  119.2 192.  239. ]
Total: 2362.0
[186.89 290.16  96.2  309.92 373.98 171.6  455.52 123.97 199.68 248.56]
Total con recargo: 2456.48
['1' 'dos' '3.0' 'True'] <U32


El array mixto sale como cadenas (`<U32`) porque un `ndarray` guarda todos sus elementos en memoria con el mismo tipo, y NumPy convierte todo al tipo más general capaz de representarlo, que aquí es texto.

In [12]:
%timeit [u * p for u, p in zip(unidades_pedido, precios_pedido)]

740 ns ± 50 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
%timeit arr_unidades * arr_precios

821 ns ± 47.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Ejercicio 9 - Subsetting con máscaras booleanas

In [14]:
son_caros = arr_precios > 100
print(son_caros)

print(arr_precios[son_caros])

print("Productos caros:", son_caros.sum())

print(importes[son_caros])
print("Suma:", importes[son_caros].sum())

print(np.where(son_caros))

hay_varias_unidades = arr_unidades >= 2
filtro_final = (arr_precios > 100) & (hay_varias_unidades)
print(filtro_final)
print(importes[filtro_final])

[False  True False  True False False  True False False  True]
[279. 149. 219. 239.]
Productos caros: 4
[279. 298. 438. 239.]
Suma: 1254.0
(array([1, 3, 6, 9]),)
[False False False  True False False  True False False False]
[298. 438.]


`son_caros.sum()` da un número porque en Python `True` vale 1 y `False` vale 0, así que sumar una máscara equivale a contar cuántos `True` hay.

## Ejercicio 10 - Matriz de ventas por trimestre y región

In [15]:
ventas_trimestrales = np.array([
    [15200.50, 11800.25, 12950.00,  9870.40, 13400.10],
    [16840.75, 12310.60, 13480.90, 11020.35, 14100.80],
    [12535.72, 10663.06, 11221.59, 12673.08, 12334.38],
])
zonas = ["Norte", "Sur", "Este", "Oeste", "Centro"]

print(ventas_trimestrales.shape, ventas_trimestrales.ndim, ventas_trimestrales.size)

print(ventas_trimestrales[1, :])
print(ventas_trimestrales[:, 4])

print(ventas_trimestrales[2, 2])

print(ventas_trimestrales[0:2, 0:3])

total_por_trimestre = ventas_trimestrales.sum(axis=1)
total_por_zona = ventas_trimestrales.sum(axis=0)
print(np.round(total_por_trimestre, 2))
print(np.round(total_por_zona, 2))

prevision_t4 = ventas_trimestrales[2, :] * 1.06
ventas_con_prevision = np.vstack([ventas_trimestrales, prevision_t4])
print(np.round(ventas_con_prevision, 2))
print(ventas_con_prevision.shape)

idx_zona_top = np.argmax(total_por_zona)
print(zonas[idx_zona_top], round(total_por_zona[idx_zona_top], 2))

(3, 5) 2 15
[16840.75 12310.6  13480.9  11020.35 14100.8 ]
[13400.1  14100.8  12334.38]
11221.59
[[15200.5  11800.25 12950.  ]
 [16840.75 12310.6  13480.9 ]]
[63221.25 67753.4  59427.83]
[44576.97 34773.91 37652.49 33563.83 39835.28]
[[15200.5  11800.25 12950.    9870.4  13400.1 ]
 [16840.75 12310.6  13480.9  11020.35 14100.8 ]
 [12535.72 10663.06 11221.59 12673.08 12334.38]
 [13287.86 11302.84 11894.89 13433.46 13074.44]]
(4, 5)
Norte 44576.97


## Ejercicio 11 - Estadística descriptiva sobre telemetría simulada

In [16]:
generador = np.random.default_rng(2024)
temperaturas = generador.normal(68, 6.5, 500)
vibraciones = np.abs(generador.normal(2.4, 0.8, 500))

media_temp = temperaturas.mean()
mediana_temp = np.median(temperaturas)
desv_temp = temperaturas.std()
print(f"Media: {media_temp:.2f} | Mediana: {mediana_temp:.2f} | Desv: {desv_temp:.2f}")
print(f"Mín: {temperaturas.min():.2f} | Máx: {temperaturas.max():.2f}")

percentiles_vibracion = np.percentile(vibraciones, [25, 50, 75, 95])
print(np.round(percentiles_vibracion, 3))

matriz_datos = np.column_stack((temperaturas, vibraciones))
print(matriz_datos.shape)

correlacion = np.corrcoef(temperaturas, vibraciones)
print(np.round(correlacion, 4))

limite_temp = media_temp + 2 * desv_temp
lecturas_altas = (temperaturas > limite_temp).sum()
print(f"Umbral: {limite_temp:.2f} | Lecturas: {lecturas_altas} | {lecturas_altas/500*100:.2f} %")

Media: 68.03 | Mediana: 68.13 | Desv: 6.50
Mín: 49.01 | Máx: 88.29
[1.895 2.394 2.925 3.73 ]
(500, 2)
[[1.     0.0067]
 [0.0067 1.    ]]
Umbral: 81.04 | Lecturas: 11 | 2.20 %


Media y mediana salen casi iguales, así que la distribución es simétrica y no hay valores raros tirando de la media hacia un lado.

La correlación sale prácticamente 0, así que temperatura y vibración no están relacionadas linealmente en estos datos (tiene sentido, las generé por separado).

Fijar la semilla (`default_rng(2024)`) hace que la secuencia de números aleatorios sea siempre la misma, así que si el profesor ejecuta esta celda le van a salir exactamente los mismos valores que a mí y puede comprobar el resultado.

## Ejercicio 12 - Diccionarios simples y anidados

In [17]:
tarifas_envio = {
    "Norte": 4.95,
    "Sur": 5.50,
    "Este": 5.20,
    "Oeste": 6.10,
    "Centro": 3.90,
}

print(tarifas_envio["Este"])

tarifas_envio["Insular"] = 9.80
tarifas_envio["Oeste"] = 5.95

del tarifas_envio["Sur"]
print("Sur" in tarifas_envio)

for zona, tarifa in tarifas_envio.items():
    print(f"{zona} -> {tarifa:.2f} €")

5.2
False
Norte -> 4.95 €
Este -> 5.20 €
Oeste -> 5.95 €
Centro -> 3.90 €
Insular -> 9.80 €


In [18]:
red_logistica = {
    "Norte":  {"almacen": "ALM-NORTE",  "tarifa": 4.95, "entrega_h": 24},
    "Este":   {"almacen": "ALM-ESTE",   "tarifa": 5.20, "entrega_h": 48},
    "Centro": {"almacen": "ALM-CENTRO", "tarifa": 3.90, "entrega_h": 24},
}

print(red_logistica["Este"]["entrega_h"])

red_logistica["Oeste"] = {"almacen": "ALM-OESTE", "tarifa": 5.95, "entrega_h": 72}

for zona, datos in red_logistica.items():
    print(f"\n--- {zona} ---")
    for campo, valor in datos.items():
        print(f"  {campo}: {valor}")

48

--- Norte ---
  almacen: ALM-NORTE
  tarifa: 4.95
  entrega_h: 24

--- Este ---
  almacen: ALM-ESTE
  tarifa: 5.2
  entrega_h: 48

--- Centro ---
  almacen: ALM-CENTRO
  tarifa: 3.9
  entrega_h: 24

--- Oeste ---
  almacen: ALM-OESTE
  tarifa: 5.95
  entrega_h: 72


Un diccionario me viene mejor cuando accedo al dato por un identificador con significado (la región, un código de producto), porque `tarifas_envio["Este"]` es directo y no depende del orden. Una lista tiene más sentido cuando lo que importa es la secuencia y los elementos son intercambiables, como una cola de pedidos que se atiende por turnos.

## Ejercicio 13 - De diccionario a DataFrame y lectura de CSV

In [19]:
almacenes_datos = {
    "codigo":    ["ALM-NORTE", "ALM-SUR", "ALM-ESTE", "ALM-OESTE", "ALM-CENTRO"],
    "ciudad":    ["Bilbao", "Sevilla", "Valencia", "Vigo", "Madrid"],
    "m2":        [4200, 3100, 3800, 2600, 6500],
    "operarios": [48, 31, 39, 22, 74],
}
almacenes = pd.DataFrame(almacenes_datos)
print(almacenes)

almacenes = almacenes.set_index("codigo")
print(almacenes)

       codigo    ciudad    m2  operarios
0   ALM-NORTE    Bilbao  4200         48
1     ALM-SUR   Sevilla  3100         31
2    ALM-ESTE  Valencia  3800         39
3   ALM-OESTE      Vigo  2600         22
4  ALM-CENTRO    Madrid  6500         74
              ciudad    m2  operarios
codigo                               
ALM-NORTE     Bilbao  4200         48
ALM-SUR      Sevilla  3100         31
ALM-ESTE    Valencia  3800         39
ALM-OESTE       Vigo  2600         22
ALM-CENTRO    Madrid  6500         74


In [20]:
ventas = pd.read_csv("../data/ventas_retail.csv")
empleados = pd.read_csv("../data/empleados.csv", index_col="id_empleado")
sensores = pd.read_csv("../data/sensores_planta.csv")

print(ventas.head(8))
print(ventas.tail(3))
print("shape:", ventas.shape)

ventas.info()

print(ventas.isna().sum())

print("ventas:", ventas.shape, "| empleados:", empleados.shape, "| sensores:", sensores.shape)

   id_pedido       fecha  region    categoria          producto  unidades  \
0  PED-10153  2025-01-01  Centro  Electronica        Tablet 10"         2   
1  PED-10030  2025-01-02     Sur      Deporte   Zapatilla Trail         4   
2  PED-10343  2025-01-02   Oeste      Oficina  Teclado Mecanico         3   
3  PED-10298  2025-01-02   Oeste        Hogar   Robot Aspirador         6   
4  PED-10144  2025-01-03     Sur      Deporte       Mochila 30L         5   
5  PED-10225  2025-01-03   Norte        Hogar   Robot Aspirador         6   
6  PED-10137  2025-01-04    Este        Hogar   Cafetera Expres         2   
7  PED-10193  2025-01-04  Centro      Deporte   Zapatilla Trail         5   

   precio_unitario  descuento_pct        canal  satisfaccion  
0            219.0             20       Tienda           3.0  
1            119.0              0       Online           5.0  
2             89.9             10       Tienda           1.0  
3            279.0             15       Tienda        

Las columnas numéricas de `ventas` son `unidades`, `precio_unitario`, `descuento_pct` y `satisfaccion`; el resto (`id_pedido`, `fecha`, `region`, `categoria`, `producto`, `canal`) son de texto. Los nulos se concentran en `canal` y `satisfaccion`; en `empleados` están en `horas_formacion` y en `sensores` en `presion_bar`.

## Ejercicio 14 - Selección con corchetes, `loc` e `iloc`

In [21]:
serie_salario = empleados["salario_base"]
frame_salario = empleados[["salario_base"]]
print(type(serie_salario))
print(type(frame_salario))

print(empleados[["departamento", "ciudad", "salario_base"]].head())

print(empleados[10:16])

print(empleados.loc["EMP-1042"])

print(empleados.loc[["EMP-1005", "EMP-1020", "EMP-1099"], ["departamento", "modalidad"]])

print(empleados.iloc[0:3, [2, 5]])

print(empleados.loc[:, ["nombre", "bonus_pct"]].head())

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
            departamento     ciudad  salario_base
id_empleado                                      
EMP-1001      Ingenieria   Valencia         43297
EMP-1002         Soporte   Valencia         32554
EMP-1003     Operaciones   Valencia         47738
EMP-1004          Ventas  Barcelona         39733
EMP-1005        Finanzas     Madrid         44990
                     nombre departamento     ciudad  antiguedad_anios  \
id_empleado                                                             
EMP-1011       Ainhoa Rojas      Soporte  Barcelona                12   
EMP-1012      Jorge Aguilar   Ingenieria     Madrid                 7   
EMP-1013      Mateo Serrano       Ventas     Madrid                15   
EMP-1014         Noa Pastor    Marketing  Barcelona                13   
EMP-1015       Ivan Aguilar     Finanzas  Barcelona                10   
EMP-1016     Valeria Ferrer   Ingenieria     Malaga                17   

             s

| Sintaxis | Trabaja por | Qué selecciona |
|---|---|---|
| `df["col"]` | Etiqueta | Una columna (o filas, si le paso un slice) |
| `df.loc[...]` | Etiqueta | Filas/columnas por nombre, rango inclusivo |
| `df.iloc[...]` | Posición | Filas/columnas por número, rango no inclusivo |

## Ejercicio 15 - Columnas calculadas, agregación y exportación

In [22]:
ventas["importe_bruto"] = ventas["unidades"] * ventas["precio_unitario"]
ventas["importe_neto"] = ventas["importe_bruto"] * (1 - ventas["descuento_pct"] / 100)
ventas["ticket_medio"] = ventas["importe_neto"] / ventas["unidades"]

print(ventas[["unidades", "precio_unitario", "descuento_pct",
              "importe_bruto", "importe_neto", "ticket_medio"]].head().round(2))

   unidades  precio_unitario  descuento_pct  importe_bruto  importe_neto  \
0         2            219.0             20          438.0        350.40   
1         4            119.0              0          476.0        476.00   
2         3             89.9             10          269.7        242.73   
3         6            279.0             15         1674.0       1422.90   
4         5             64.0             20          320.0        256.00   

   ticket_medio  
0        175.20  
1        119.00  
2         80.91  
3        237.15  
4         51.20  


In [23]:
facturacion_por_zona = ventas.groupby("region")["importe_neto"].sum().sort_values(ascending=False)
print(facturacion_por_zona.round(2))
print("Facturación total:", round(ventas["importe_neto"].sum(), 2))

region
Norte     44576.97
Centro    39835.28
Este      37652.49
Sur       34773.91
Oeste     33563.83
Name: importe_neto, dtype: float64
Facturación total: 190402.48


In [24]:
resumen_cat_canal = ventas.groupby(["categoria", "canal"]).agg({
    "importe_neto": "mean",
    "unidades": "sum",
}).round(2)
print(resumen_cat_canal)

                         importe_neto  unidades
categoria   canal                              
Deporte     Marketplace        311.65       111
            Online             292.23       225
            Tienda             189.06       157
Electronica Marketplace        427.72        95
            Online             426.70       242
            Tienda             419.82       199
Hogar       Marketplace        665.55        82
            Online             447.14       278
            Tienda             889.92       145
Oficina     Marketplace        752.75        83
            Online             480.24       179
            Tienda             597.19       124


In [25]:
top5_productos = ventas.groupby("producto")["importe_neto"].sum().nlargest(5)
print(top5_productos.round(2))

producto
Robot Aspirador     32322.15
Tablet 10"          24068.10
Silla Ergonomica    22394.30
Smartwatch S2       20316.15
Cafetera Expres     19778.85
Name: importe_neto, dtype: float64


In [26]:
mediana_satisfaccion = ventas["satisfaccion"].median()
print("Mediana satisfacción:", mediana_satisfaccion)

ventas["satisfaccion"] = ventas["satisfaccion"].fillna(mediana_satisfaccion)
ventas["canal"] = ventas["canal"].fillna("Desconocido")
print(ventas[["satisfaccion", "canal"]].isna().sum())
print(ventas["canal"].value_counts())

facturacion_por_zona.round(2).to_csv("../outputs/facturacion_por_region.csv", header=["importe_neto"])
print("Exportado a ../outputs/facturacion_por_region.csv")

Mediana satisfacción: 3.0
satisfaccion    0
canal           0
dtype: int64
canal
Online         206
Tienda         137
Marketplace     72
Desconocido      5
Name: count, dtype: int64
Exportado a ../outputs/facturacion_por_region.csv


## Ejercicio 16 - Operadores de comparación y booleanos

In [27]:
print(2 < 3)
print("Norte" == "norte")
print(True + True + False)
print(3 != 3.0)
print("Zapatilla" > "Mochila")

True
False
2
False
True


1. `2 < 3` → True, comparación numérica normal.
2. `"Norte" == "norte"` → False, las cadenas se comparan distinguiendo mayúsculas.
3. `True + True + False` → 2, porque en Python `bool` es un `int` (True=1, False=0).
4. `3 != 3.0` → False, Python compara el valor, no el tipo.
5. `"Zapatilla" > "Mochila"` → True, orden alfabético letra a letra.

In [28]:
unidades_ej = 6
precio_ej = 149.0
descuento_ej = 15

pedido_grande_con_descuento = (unidades_ej > 4) and (descuento_ej >= 10)
print(pedido_grande_con_descuento)

precio_fuera_de_rango = (precio_ej < 50) or (precio_ej > 200)
print(precio_fuera_de_rango)

print(not pedido_grande_con_descuento)

True
False
False


Que `not pedido_grande_con_descuento` sea False significa que este pedido sí entra en el grupo de volumen alto con descuento relevante, así que conviene revisarlo por margen.

In [29]:
temp_sensor = np.array([64.2, 88.1, 71.0, 92.5, 69.8])
vib_sensor = np.array([1.9, 3.4, 2.1, 4.0, 2.2])

try:
    print(temp_sensor > 70 and vib_sensor > 3)
except ValueError as e:
    print("ValueError:", e)

r1 = np.logical_and(temp_sensor > 70, vib_sensor > 3)
r2 = (temp_sensor > 70) & (vib_sensor > 3)
print(r1)
print(r2)
print(np.array_equal(r1, r2))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[False  True False  True False]
[False  True False  True False]
True


## Ejercicio 17 - `if`/`elif`/`else` aplicado a mantenimiento predictivo

In [30]:
def nivel_riesgo(temp):
    if temp > 85:
        return "CRÍTICO"
    elif temp > 76:
        return "ALTO"
    elif temp > 70:
        return "MEDIO"
    else:
        return "BAJO"


for t in [92.5, 80.0, 72.3, 64.1]:
    print(t, "->", nivel_riesgo(t))

92.5 -> CRÍTICO
80.0 -> ALTO
72.3 -> MEDIO
64.1 -> BAJO


In [31]:
sensores["riesgo"] = sensores["temperatura_c"].apply(nivel_riesgo)
print(sensores[["id_maquina", "temperatura_c", "riesgo"]].head())

print(sensores["riesgo"].value_counts())

criticos = sensores[sensores["riesgo"] == "CRÍTICO"]
print("Lecturas críticas:", len(criticos))
print(criticos["id_maquina"].value_counts())

print(sensores["estado"].value_counts())

  id_maquina  temperatura_c riesgo
0     MAQ-01          58.92   BAJO
1     MAQ-03          71.72  MEDIO
2     MAQ-02          67.93   BAJO
3     MAQ-03          73.10  MEDIO
4     MAQ-03          69.37   BAJO
riesgo
BAJO       347
MEDIO      161
ALTO        72
CRÍTICO     20
Name: count, dtype: int64
Lecturas críticas: 20
id_maquina
MAQ-04    6
MAQ-02    5
MAQ-01    5
MAQ-03    4
Name: count, dtype: int64
estado
OK        508
AVISO      72
ALARMA     20
Name: count, dtype: int64


Las lecturas críticas se reparten entre varias máquinas, así que el problema parece de planta (refrigeración o carga de trabajo) y no de una sola máquina defectuosa. Propongo revisar la refrigeración de ambas líneas y avisar automáticamente en el umbral de 76 °C, antes de que los avisos escalen a alarma.

## Ejercicio 18 - Filtrado avanzado de DataFrames

In [32]:
pedidos_online_caros = ventas[(ventas["canal"] == "Online") & (ventas["importe_neto"] > 500)]
print("Online > 500 €:", len(pedidos_online_caros))
print(pedidos_online_caros[["id_pedido", "region", "producto", "importe_neto"]].head())

pedidos_norte_centro = ventas[ventas["region"].isin(["Norte", "Centro"])]
print("Norte o Centro:", len(pedidos_norte_centro))

pedidos_descuento_medio = ventas[ventas["descuento_pct"].between(10, 20)]
print("Descuento 10-20%:", len(pedidos_descuento_medio))

pedidos_electronica_filtrados = ventas[
    (ventas["categoria"] == "Electronica")
    & (ventas["unidades"] > 2)
    & (ventas["descuento_pct"] != 0)
]
print("Electrónica filtrada:", len(pedidos_electronica_filtrados))

pedidos_no_oficina = ventas[~(ventas["categoria"] == "Oficina")]
print("No Oficina:", len(pedidos_no_oficina))

pedidos_online_caros_query = ventas.query("canal == 'Online' and importe_neto > 500")
print("query coincide:", len(pedidos_online_caros_query) == len(pedidos_online_caros))

Online > 500 €: 61
    id_pedido  region          producto  importe_neto
7   PED-10193  Centro   Zapatilla Trail        595.00
16  PED-10183   Oeste   Robot Aspirador        711.45
22  PED-10130    Este        Tablet 10"       1664.40
23  PED-10149    Este   Robot Aspirador        837.00
28  PED-10057  Centro  Teclado Mecanico        539.40
Norte o Centro: 185
Descuento 10-20%: 168
Electrónica filtrada: 52
No Oficina: 333
query coincide: True


`.query()` se lee casi como una frase y admite `and`/`or` directamente, mientras que la sintaxis con corchetes es más verbosa pero acepta cualquier expresión de Python.

In [33]:
ingenieria_remoto_senior = empleados[
    (empleados["departamento"] == "Ingenieria")
    & (empleados["modalidad"] == "Remoto")
    & (empleados["antiguedad_anios"] > 5)
].sort_values("salario_base", ascending=False)

print(ingenieria_remoto_senior)
print(ingenieria_remoto_senior.shape)

ingenieria_remoto_senior.to_csv("../outputs/ingenieria_remoto_senior.csv")

                   nombre departamento  ciudad  antiguedad_anios  \
id_empleado                                                        
EMP-1007     Marcos Rojas   Ingenieria  Malaga                 7   

             salario_base  bonus_pct modalidad  horas_formacion  
id_empleado                                                      
EMP-1007            50114         12    Remoto             57.0  
(1, 8)


## Ejercicio 19 - Bucles sobre estructuras de datos

In [34]:
stock_actual = 12
num_lote = 0

while stock_actual < 60:
    num_lote += 1
    stock_actual += 8
    print("Lote", num_lote, "-> stock:", stock_actual)

Lote 1 -> stock: 20
Lote 2 -> stock: 28
Lote 3 -> stock: 36
Lote 4 -> stock: 44
Lote 5 -> stock: 52
Lote 6 -> stock: 60


In [35]:
zonas_envio = ["Norte", "Sur", "Este", "Oeste", "Centro"]
for zona in zonas_envio:
    print(zona.upper())

NORTE
SUR
ESTE
OESTE
CENTRO


In [36]:
for i, zona in enumerate(zonas_envio, start=1):
    print(f"Región {i}: {zona}")

Región 1: Norte
Región 2: Sur
Región 3: Este
Región 4: Oeste
Región 5: Centro


In [37]:
for almacen, producto, unidades, coste in inventario:
    print(almacen, "|", producto, "|", round(unidades * coste, 2), "€")

ALM-NORTE | Robot Aspirador | 6851.0 €
ALM-NORTE | Monitor 27 | 8236.0 €
ALM-SUR | Silla Ergonomica | 2146.8 €
ALM-SUR | Robot Aspirador | 1410.5 €
ALM-ESTE | Cafetera Expres | 5379.2 €
ALM-ESTE | Monitor 27 | 3550.0 €


In [38]:
for zona, tarifa in tarifas_envio.items():
    print(f"{zona}: {tarifa:.2f} €")

Norte: 4.95 €
Este: 5.20 €
Oeste: 5.95 €
Centro: 3.90 €
Insular: 9.80 €


In [39]:
for precio in arr_precios:
    print(round(precio * 1.04, 2))

62.3
290.16
19.24
154.96
93.5
28.6
227.76
15.5
66.56
248.56


Al recorrer un diccionario directamente solo obtengo las claves; con `.items()` recibo cada clave junto con su valor, que es lo que necesito para desempaquetar los dos en el bucle.

## Ejercicio 20 - Iteración sobre DataFrames

In [40]:
for etiqueta, fila in ventas.head(5).iterrows():
    print(fila["region"], "|", fila["producto"], "|", round(fila["importe_neto"], 2), "€")

Centro | Tablet 10" | 350.4 €
Sur | Zapatilla Trail | 476.0 €
Oeste | Teclado Mecanico | 242.73 €
Oeste | Robot Aspirador | 1422.9 €
Sur | Mochila 30L | 256.0 €


In [41]:
ventas["codigo_region"] = ventas["region"].str[:3].str.upper()
print(ventas[["region", "codigo_region"]].head())

   region codigo_region
0  Centro           CEN
1     Sur           SUR
2   Oeste           OES
3   Oeste           OES
4     Sur           SUR


In [42]:
import sys
sys.path.append("../src")
from utilidades import clasificar_ticket

ventas["segmento_ticket"] = ventas["importe_neto"].apply(clasificar_ticket)
print(ventas[["importe_neto", "segmento_ticket"]].head().round(2))

print(ventas["segmento_ticket"].value_counts())

   importe_neto segmento_ticket
0        350.40           Medio
1        476.00            Alto
2        242.73           Medio
3       1422.90            Alto
4        256.00           Medio
segmento_ticket
Alto     167
Medio    152
Bajo     101
Name: count, dtype: int64


In [43]:
sensores["eficiencia"] = (sensores["unidades_producidas"] / sensores["temperatura_c"]).round(3)
print(sensores[["id_maquina", "unidades_producidas", "temperatura_c", "eficiencia"]].head())

  id_maquina  unidades_producidas  temperatura_c  eficiencia
0     MAQ-01                  141          58.92       2.393
1     MAQ-03                  153          71.72       2.133
2     MAQ-02                  117          67.93       1.722
3     MAQ-03                  105          73.10       1.436
4     MAQ-03                   85          69.37       1.225


In [44]:
resumen_por_zona = {}

for zona in ventas["region"].unique():
    filtrado_zona = ventas[ventas["region"] == zona]
    resumen_por_zona[zona] = round(filtrado_zona["importe_neto"].sum(), 2)

print(resumen_por_zona)

comparativa_groupby = ventas.groupby("region")["importe_neto"].sum().round(2)
print(comparativa_groupby)
print(all(comparativa_groupby[z] == resumen_por_zona[z] for z in resumen_por_zona))

{'Centro': np.float64(39835.28), 'Sur': np.float64(34773.91), 'Oeste': np.float64(33563.83), 'Norte': np.float64(44576.97), 'Este': np.float64(37652.49)}
region
Centro    39835.28
Este      37652.49
Norte     44576.97
Oeste     33563.83
Sur       34773.91
Name: importe_neto, dtype: float64
True


Prefiero `.groupby("region")["importe_neto"].sum()`: hace lo mismo en una sola línea y recorre el DataFrame una vez, mientras que mi bucle vuelve a filtrar todo el DataFrame en cada vuelta.